version: '3.8'

services:
  mongodb:
    image: mongo:latest
    container_name: easyshop-mongodb
    env_file:
      - .env.local
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    healthcheck:
      test: ["CMD-SHELL", "echo 'db.adminCommand(\"ping\")' | mongosh --quiet"]
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 30s
    deploy:
      resources:
        limits:
          memory: 2G
          cpus: "1.0"
        reservations:
          memory: 1G
          cpus: "0.5"
    networks:
      - easyshop-network

  migration:
    build:
      context: .
      dockerfile: scripts/Dockerfile.migration
    container_name: easyshop-migration
    env_file:
      - .env.local
    depends_on:
      mongodb:
        condition: service_healthy
    networks:
      - easyshop-network

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: easyshop
    ports:
      - "3000:3000"
    env_file:
      - .env.local
    depends_on:
      migration:
        condition: service_completed_successfully
    networks:
      - easyshop-network
    restart: always

networks:
  easyshop-network:
    name: easyshop-network

volumes:
  mongodb_data:
    driver: local