{{- if .Values.ingress.tls.enabled }}
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: {{ .Values.app.name }}-letsencrypt
  labels:
    {{- include "easyshop.labels" . | nindent 4 }}
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: {{ .Values.ingress.tls.email | default "admin@example.com" }}
    privateKeySecretRef:
      name: {{ .Values.app.name }}-letsencrypt-key
    solvers:
    - http01:
        ingress:
          class: {{ .Values.ingress.className }}
{{- end }}