apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.app.name }}
  namespace: {{ .Values.app.namespace }}
  labels:
    {{- include "easyshop.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.app.replicas }}
  selector:
    matchLabels:
      {{- include "easyshop.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "easyshop.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: {{ .Values.app.name }}
          image: "{{ .Values.app.image.repository }}:{{ .Values.app.image.tag }}"
          imagePullPolicy: {{ .Values.app.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.app.containerPort }}
              protocol: TCP
          env:
            - name: MONGODB_URI
              valueFrom:
                configMapKeyRef:
                  name: {{ .Values.app.name }}-config
                  key: MONGODB_URI
            - name: NODE_ENV
              valueFrom:
                configMapKeyRef:
                  name: {{ .Values.app.name }}-config
                  key: NODE_ENV
            - name: NEXT_PUBLIC_API_URL
              valueFrom:
                configMapKeyRef:
                  name: {{ .Values.app.name }}-config
                  key: NEXT_PUBLIC_API_URL
            - name: NEXTAUTH_URL
              valueFrom:
                configMapKeyRef:
                  name: {{ .Values.app.name }}-config
                  key: NEXTAUTH_URL
          resources:
            {{- toYaml .Values.app.resources | nindent 12 }}
          startupProbe:
            httpGet:
              path: {{ .Values.app.probes.startup.path }}
              port: http
            failureThreshold: {{ .Values.app.probes.startup.failureThreshold }}
            periodSeconds: {{ .Values.app.probes.startup.periodSeconds }}
          readinessProbe:
            httpGet:
              path: {{ .Values.app.probes.readiness.path }}
              port: http
            initialDelaySeconds: {{ .Values.app.probes.readiness.initialDelaySeconds }}
            periodSeconds: {{ .Values.app.probes.readiness.periodSeconds }}
          livenessProbe:
            httpGet:
              path: {{ .Values.app.probes.liveness.path }}
              port: http
            initialDelaySeconds: {{ .Values.app.probes.liveness.initialDelaySeconds }}
            periodSeconds: {{ .Values.app.probes.liveness.periodSeconds }}
      imagePullSecrets:
        - name: regcred
