apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.app.name }}-secrets
  namespace: {{ .Values.app.namespace }}
  labels:
    {{- include "easyshop.labels" . | nindent 4 }}
type: Opaque
data:
  JWT_SECRET: {{ .Values.secrets.jwtSecret | b64enc | quote }}
  NEXTAUTH_SECRET: {{ .Values.secrets.nextAuthSecret | b64enc | quote }}